# Copyright (C) 2018 Radiant Solutions (http://www.radiantsolutions.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# The base image depends on the version of PosgreSQL from PGDG.
ARG pg_version
FROM hootenanny/rpmbuild-pgdg:${pg_version}

LABEL \
  description="Container for building Hootenanny RPMs" \
  maintainer="justin.bronn@radiantsolutions.com" \
  name="Hootenanny Release RPM Build Image" \
  vendor="Radiant Solutions"

ARG mocha_version
ARG nodejs_version
ARG packages
ARG pg_version
ARG pg_data=/var/lib/pgsql/${pg_version}/data

# Have PostgreSQL data directory persist in environment variable.
ENV PGDATA=${pg_data}

# Switch back to root.
USER root

# Install Hootenanny release repository, NodeJS and pin to desired version.
COPY scripts/hoot-repo.sh scripts/nodejs-install.sh /tmp/
RUN /tmp/hoot-repo.sh && \
    rm /tmp/hoot-repo.sh && \
    /tmp/nodejs-install.sh ${nodejs_version} && \
    rm -f /tmp/nodejs-install.sh && \
    npm install --silent -g mocha@${mocha_version}

# Install Hootenanny dependencies.
RUN yum install -y -q dumb-init su-exec tomcat8 && \
    if [ ! -z "${packages}" ] ; then yum -y -q install ${packages}; fi

# Install PostgreSQL server at desired version, and setup the Hoot databases.
COPY scripts/hoot-db-setup.sh scripts/postgresql-install.sh /tmp/
RUN /tmp/postgresql-install.sh && \
    rm -f /tmp/postgresql-install.sh && \
    /tmp/hoot-db-setup.sh && \
    rm -f /tmp/hoot-db-setup.sh && \
    yum -q -y clean all

# Copy in the entrypoint.
COPY scripts/build-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash"]
