# Copyright (C) 2018-2021 Maxar Technologies (https://www.maxar.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
FROM hootenanny/rpmbuild
LABEL \
  description="Base container for building Hootenanny RPMs" \
  maintainer="justin.bronn@maxar.com" \
  name="Hootenanny Base RPM Build Image" \
  vendor="Maxar Technologies"

# Install basic development and RPM authoring tools.
SHELL ["/bin/bash", "-c"]
RUN dnf -q -y install epel-release && \
    dnf -q -y update && \
    dnf -q -y install \
        autoconf \
        autoconf-archive \
        automake \
        bzip2 \
        gcc \
        gcc-c++ \
        git \
        git-core \
        libtool \
        parallel \
        m4 \
        redhat-rpm-config \
        rpm-build \
        rpmdevtools \
        rpmlint \
        unzip \
        vim \
        wget \
        zip && \
    dnf -q -y clean all
