FROM hootenanny/rpmbuild-hoot-release:latest

LABEL \
  description="Sonarqube Scanning Container for Hootenanny" \
  maintainer="justin.bronn@radiantsolutions.com" \
  name="Hootenanny Sonarqube Image" \
  vendor="Radiant Solutions"

COPY scripts/sonar-install.sh /tmp/sonar-install.sh
COPY scripts/sonar-build.sh /usr/local/bin/sonar-build.sh
RUN /tmp/sonar-install.sh && rm /tmp/sonar-install.sh
