# The base image depends on the version of PosgreSQL from PGDG.
ARG pg_version
FROM hoot/rpmbuild-pgdg:${pg_version}

ARG node_version
ARG packages
ARG pg_version
ARG pg_data=/var/lib/pgsql/${pg_version}/data

LABEL \
  description="Container for building Hootenanny RPMs" \
  maintainer="justin.bronn@digitalglobe.com" \
  name="Hootenanny Release RPM Build Image" \
  vendor="Radiant Solutions"

USER root

# Copy in repository setup scripts.
COPY scripts/hoot-repo.sh scripts/nodesource-repo.sh /tmp/

# Install NodeJS and pin to desired version.
RUN /tmp/nodesource-repo.sh ${node_version} && \
    rm /tmp/nodesource-repo.sh && \
    yum install -q -y \
      nodejs-${node_version} \
      nodejs-devel-${node_version} \
      yum-plugin-versionlock && \
    yum versionlock nodejs*

# Install Hootenanny release repository and dependencies.
RUN /tmp/hoot-repo.sh && \
    rm /tmp/hoot-repo.sh && \
    yum install -y -q su-exec && \
    if [ ! -z "${packages}" ] ; then yum -y -q install ${packages}; fi

# Install PostgreSQL server at desired version.
RUN yum -q -y install postgresql$(echo ${pg_version} | tr -d '.')-server && \
    alternatives --install /usr/bin/initdb pgsql-initdb /usr/pgsql-${pg_version}/bin/initdb 500 && \
    alternatives --install /usr/bin/pg_ctl pgsql-pg_ctl /usr/pgsql-${pg_version}/bin/pg_ctl 500 && \
    su-exec postgres:postgres initdb -D ${pg_data} --locale ${LANG}

# Set default user and work directory.
USER ${RPMBUILD_USER}
WORKDIR ${RPMBUILD_HOME}

# Make directory for Hootenanny source code.
RUN mkdir -p ${RPMBUILD_HOME}/hoot
