# -*- mode: ruby -*-
# vi: set ft=ruby :

$provisionSh = <<-SHELL
    if ! yum list installed | grep --quiet createrepo ; then
      # Install createrepo. The actual drive mounting and work is done in the VagrantLocal scripts
      sudo yum -y -q install createrepo
    fi
SHELL


Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: $provisionSh

end

# Allow local overrides of vagrant settings
if File.exists?('VagrantfileLocal')
  load 'VagrantfileLocal'
else
  load 'VagrantfileLocal.vbox'
end
